version: '3'
services:  
  exporter:
    container_name: exporter
    image: nginx/nginx-prometheus-exporter
    ports:
      - 9113:9113
    command:
      - -nginx.scrape-uri=http://localhost:8080/metrics